name: Swift Windows CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test-windows:
    name: Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
        with:
          persist-credentials: false
      - name: Setup Swift
        uses: SwiftyLab/setup-swift@38f54a76b70d989321de9dc7c840618c08cf56e9 #1.14.0
        with:
          swift-version: "6.3.2"

      - name: Test
        shell: bash
        run: swift test